### ISSUE TITLE
devtools::install_github("kazutan/tubeplayR")でインストールできない

### ISSUE THREAD

**Issue by indenkun** [kazutan/tubeplayR#6]
devtools::install_github("kazutan/tubeplayR")でインストできない状態になっています。

windows 10 R3.6.3、RStudio1.2.5001および1.2.5042の実機端末、
windows 10 R4.0.0、RStudio1.2.5042の複数実機端末で再現できています。

エラーメッセージは
```r
devtools::install_github("kazutan/tubeplayR")
Downloading GitHub repo kazutan/tubeplayR@master
√  checking for file  (711ms)
-  preparing 'tubeplayR':
√  checking DESCRIPTION meta-information ... 
-  cleaning src
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'tubeplayR_0.1.3.tar.gz'
   
Installing package into ‘/R/win-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package 'tubeplayR' ...
** using staged installation
** libs

*** arch - i386
DLLは生成されませんでした 
ERROR: compilation failed for package 'tubeplayR'
```
となっています。
リポジトリをクローンしてローカルでソースパッケージをビルドしてみてもほぼ同様のエラーがでました。

これはsrc/picsの存在が一因ではないかと思っています。

ローカルでソースパッケージをビルドする際の回避策として、src/に.cppなどないので.Rbuildignoreに^srcまたは^src/picsと記載しソースパッケージをビルドする際に画像ファイルをソースパッケージを内に含まないようにすることで作成できたソースパッケージをからバイナリビルドできました。
または、pics/以下をsrc/外に出すことでバイナリビルドできました。

インストールできれば正しく挙動しました。

install_github()の挙動について明るくないので上記がdevtools::install_github("kazutan/tubeplayR")でインストできない原因と解決策になるのかはわかりませんがご一考ください。

**Comment by kazutan** [comment]
@indenkun 
ありがとうございます。
あなたが指摘した点について、すぐに修正したいと思います。
